### ISSUE TITLE
free/open source license?

### ISSUE THREAD

**Issue by slivingston** [mkhaled87/scots-ready#1]
This is a fork of <https://gitlab.lrz.de/hcs/scots>, but it seems that [the original license file](https://gitlab.lrz.de/hcs/scots/-/blob/d9f8ebadbd19cdd215a0cd83b9965f3ad45d4409/license.txt) is missing. Can you add it, or am I missing something?

**Comment by mkhaled87** [comment]
You are absolutely right. This was missed from the first commit. Will add it now.

**Comment by mkhaled87** [comment]
Done!

**Comment by slivingston** [comment]
Thanks for this and your work on the list at <https://ieeecss.org/tc/hybrid-systems/tools>!

**Comment by mkhaled87** [comment]
You are always welcome!
